package com.wjduquette.joe.bert;

/**
 * A memory cell supporting assignment and retrieval.  This is used
 * to simply generated byte-code for `Upvalues` and for operators
 * that both set and get a memory location with complicated access
 * (e.g., properties, indexes).
 */
public interface Cell {
    /**
     * Gets the cell's value.
     * @return The value
     */
    Object get();

    /**
     * Sets the cells's value.
     * @param value The value
     */
    void set(Object value);
}
