package com.wjduquette.joe.scanner;

/**
 * The {@link Token} types that can be returned by the {@link Tokenizer}.
 */
public enum TokenType {
    // Single-character tokens.
    /** "(" */  LEFT_PAREN,
    /** ")" */  RIGHT_PAREN,
    /** "{" */  LEFT_BRACE,
    /** "}" */  RIGHT_BRACE,
    /** "[" */  LEFT_BRACKET,
    /** "]" */  RIGHT_BRACKET,
    /** "@" */  AT,
    /** "\" */  BACK_SLASH,
    /** ":" */  COLON,
    /** "," */  COMMA,
    /** "$" */  DOLLAR,
    /** "?" */  QUESTION,
    /** ";" */  SEMICOLON,
    /** "~" */  TILDE,

    // One or multiple character tokens.
    /** "&amp;&amp;" */  AND,
    /** "!" */   BANG,
    /** "!=" */  BANG_EQUAL,
    /** ":-" */  COLON_MINUS,
    /** "." */   DOT,
    /** "..." */ DOT_DOT_DOT,
    /** "=" */   EQUAL,
    /** "==" */  EQUAL_EQUAL,
    /** "&gt;" */   GREATER,
    /** "&gt;=" */  GREATER_EQUAL,
    /** "-" */   MINUS,
    /** "-=" */  MINUS_EQUAL,
    /** "-&gt;" */  MINUS_GREATER,
    /** "--" */  MINUS_MINUS,
    /** "&lt;" */   LESS,
    /** "&lt;=" */  LESS_EQUAL,
    /** "|" */   PIPE,
    /** "||" */  OR,
    /** "+" */   PLUS,
    /** "+=" */  PLUS_EQUAL,
    /** "++" */  PLUS_PLUS,
    /** "/" */   SLASH,
    /** "/=" */  SLASH_EQUAL,
    /** "*" */   STAR,
    /** "*=" */  STAR_EQUAL,

    // Literals.
    /** Literal */ IDENTIFIER,
    /** Literal */ STRING,
    /** Literal */ NUMBER,
    /** Literal */ KEYWORD,

    // Reserved Words.
    /** Reserved word */ ASSERT,
    /** Reserved word */ BREAK,
    /** Reserved word */ CASE,
    /** Reserved word */ CLASS,
    /** Reserved word */ CONTINUE,
    /** Reserved word */ DEFAULT,
    /** Reserved word */ ELSE,
    /** Reserved word */ EXPORT,
    /** Reserved word */ EXTENDS,
    /** Reserved word */ FALSE,
    /** Reserved word */ FOR,
    /** Reserved word */ FOREACH,
    /** Reserved word */ FUNCTION,
    /** Reserved word */ IF,
    /** Reserved word */ IMPORT,
    /** Reserved word */ IN,
    /** Reserved word */ LET,
    /** Reserved word */ MATCH,
    /** Reserved word */ METHOD,
    /** Reserved word */ NI,
    /** Reserved word */ NOT,
    /** Reserved word */ NULL,
    /** Reserved word */ RECORD,
    /** Reserved word */ RETURN,
    /** Reserved word */ RULESET,
    /** Reserved word */ STATIC,
    /** Reserved word */ SUPER,
    /** Reserved word */ SWITCH,
    /** Reserved word */ THIS,
    /** Reserved word */ THROW,
    /** Reserved word */ TRUE,
    /** Reserved word */ VAR,
    /** Reserved word */ WHERE,
    /** Reserved word */ WHILE,

    /** Indicates error. */        ERROR,
    /** Indicates end of input. */ EOF
}
